# Generated by Django 3.2.19 on 2023-07-04 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cipgblog', '0002_alter_comments_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
